### ISSUE TITLE
Last history entry is not shown

### ISSUE THREAD

**Issue by petobens** [neoclide/denite-extra#1]
@chemzqm thanks for writing a history source! 
There is one minor nit: the very last history entry is not displayed as candidate: i.e if for instance you run `/foo` and then `:Denite history:search` then `foo` does not show as a candidate.
Any chance of fixing this? Once again thanks.

**Comment by petobens** [comment]
Also is it possible to prefix a `:` to the command history source? Currently the candidates are shown as `echo 'foo'` and I would like them to be shown as `:echo 'foo'`.

**Comment by chemzqm** [comment]
@petobens  good idea

**Comment by petobens** [comment]
Thank you!

**Comment by petobens** [comment]
@chemzqm if i 
i) run `Denite history:cmd`
ii) select a candidate and press `<CR>`
iii) run `Denite history:cmd` again 

In the last step the selected command is not shown as the first candidate:

![jul-23-2017 13-51-44](https://user-images.githubusercontent.com/2583971/28501243-1e93372e-6fae-11e7-836c-7340365e0272.gif)

**Comment by chemzqm** [comment]
The command is executed by `execute` command, not the user, so vim's history won't change, you can use `feedkeys` action to change the behaviour.
