### ISSUE TITLE
Better document how to use actions 

### ISSUE THREAD

**Issue by danielo515** [neoclide/denite-extra#10]
Hello.
It is not clear how actions should be used. 
I'm not sure if I have to create new denite actions or with the provided name or if the listed actions are triggered on default denite calls... I just tried default denite action (cr) in sessions and it does what is described on load. So, how is this supposed to be used?

**Comment by chemzqm** [comment]
Use `<tab>` to get available actions.

**Comment by danielo515** [comment]
Oh, awesome. Thank you
