### ISSUE TITLE
Some (minor) issues with history source

### ISSUE THREAD

**Issue by petobens** [neoclide/denite-extra#7]
Hi! I was wondering if you could change/fix two minor nits I've recently noticed with the history source:

i) the `history:cmd` source default action (execute) doesn't seem to work with `echo 'foo'` or `:messages`
ii) is it possible to open folds with the `history:search` source?

Thanks in advnace!

**Comment by Shougo** [comment]
> i) the history:cmd source default action (execute) doesn't seem to work with echo 'foo' or :messages

`action__is_pause` must be set for it.

**Comment by chemzqm** [comment]
@petobens I tried `echom 'foo'`, it could work and can be checked by `:messages`,  but the command line is refresh when denite buffer closed afterward.

**Comment by petobens** [comment]
@chemzqm I'm not quite following what you said. In the next gif I try the `echom 'foo'` example and I don't see any output after executing the default action on the candidate:
![jul-08-2018 12-18-40](https://user-images.githubusercontent.com/2583971/42421278-43bebf96-82a9-11e8-8183-c3cdc4a61f53.gif)

**Comment by petobens** [comment]
@Shougo using `Denite command_history` I indeed see an ouput from `echom 'foo'` (as in the following GIF). Can the source candidate  be shown without the preceding number and with a preceding `:` as Denite history:cmd source does? i.e changing:
```
123 echom 'foo' 
```
to
```
:echom 'foo'
```
Thank you!
![jul-08-2018 12-18-40](https://user-images.githubusercontent.com/2583971/42421323-1951991c-82aa-11e8-9428-e00ad8496303.gif)

**Comment by Shougo** [comment]
> @petobens I tried echom 'foo', it could work and can be checked by :messages, but the command line is refresh when denite buffer closed afterward.

Have you read my message?
It is feature of denite.
So denite-extra must set `action__is_pause` for it.

**Comment by Shougo** [comment]
denite uses command line to display the prompt.
So, it will be cleared when denite buffer closed.

**Comment by Shougo** [comment]
>  using Denite command_history I indeed see an ouput from echom 'foo' (as in the following GIF). 

Because, it set `action__is_pause`.

> an the source candidate be shown without the preceding number and with a preceding : as Denite history:cmd source does?

OK.  I have changed it.

**Comment by chemzqm** [comment]
I have set `action__is_pause` to true, but I didn't notice any difference.

**Comment by Shougo** [comment]
> I have set action__is_pause to true, but I didn't notice any difference.

It works for me.
Have you set it in the candidates?

It works only to print candidates and `command` kind.

**Comment by Shougo** [comment]
https://github.com/neoclide/denite-extra/blob/master/rplugin/python3/denite/source/history.py#L19

It is not command kind.
It does not work.

**Comment by chemzqm** [comment]
Didn't notice that, should be fixed.

**Comment by petobens** [comment]
@Shougo @chemzqm thanks to both of you!

@chemzqm regarding:
>  ii) is it possible to open folds with the history:search source?

Do you think that the behaviour can me changed?
